nbastockmarket/market/urls.py
from django.urls import path, re_path
from django.conf.urls import url

from . import views
from django.contrib.auth import views as auth_views


# not sure, if these should be here or project urls.py, the quickstart tutorial says here explicitly, but on the rest framework home page
    # it implies it should at the project urls.py
from django.urls import include, path
from rest_framework import routers
from market import views # even though on the tutorial it says project.application
from rest_framework.urlpatterns import format_suffix_patterns
from market.views import UserViewSet, GroupViewSet, PlayerViewSet, VSUserViewSet, PlayerHistoricalStatisticsViewSet, PlayerCurrentStatisticsViewSet, ShareViewSet, WatchlistDetailViewSet, UserMarketDetailsViewSet, TeamViewSet, GameViewSet, MarketViewSet
from rest_framework import renderers
from rest_framework.routers import DefaultRouter



app_name = 'market'
# handler404 = 'market.views.my_custom_page_not_found_view'
# handler500 = 'market.views.my_custom_error_view'
# handler403 = 'market.views.my_custom_permission_denied_view'
# handler400 = 'market.views.my_custom_bad_request_view'


# Rest Framework API
# not sure, if these should be here or project urls.py, the quickstart tutorial says here explicitly, but on the rest framework home page
# it implies it should at the project urls.py
# router = routers.DefaultRouter()
# router.register(r'users', UserViewSet)
# router.register(r'groups', views.GroupViewSet) # not created yet
# router.register(r'players', views.PlayerViewSet)
# router.register(r'vsusers', views.VSUserViewSet)
# router.register(r'playerhistoricalstatistics', views.PlayerHistoricalStatisticsViewSet)
# router.register(r'playercurrentstatistics', views.PlayerCurrentStatisticsViewSet)
# router.register(r'shares', views.ShareViewSet)
# router.register(r'watchlistdetails', views.WatchlistDetailViewSet)
# router.register(r'usermarketdetails', views.UserMarketDetailsViewSet)
# router.register(r'teams', views.TeamViewSet)
# router.register(r'games', views.GameViewSet)
# router.register(r'markets', views.MarketViewSet)



# player_list = PlayerViewSet.as_view({
#     'get': 'list',
#     'post': 'create'
# })
# player_detail = PlayerViewSet.as_view({
#     'get': 'retrieve',
#     'put': 'update',
#     'patch': 'partial_update',
#     'delete': 'destroy'
# })
# player_team = PlayerViewSet.as_view({
#     'get': 'team'
# }, renderer_classes=[renderers.StaticHTMLRenderer])
# user_list = UserViewSet.as_view({
#     'get': 'list'
# })
# user_detail = UserViewSet.as_view({
#     'get': 'retrieve'
# })


urlpatterns = [
    # ex /polls/
    path('', views.index, name='index'),
    # path('login/', views.login, name='login'),
    
    # ex /polls/5/
    path('<int:player_id>/', views.detail, name='player_detail'),
    # ex: /polls/5/results/
    # path('<int:pk>/results/', views.results, name='results'),
    # ex: /polls/5/buy/
    path('<int:player_id>/buy/', views.buy, name='buy'),
    path('<int:player_id>/sell/', views.sell, name='sell'),
    path('<int:player_id>/watchlist_add/', views.addToWatchlist, name='watchlist_add'),
    path('<int:player_id>/watchlist_remove/', views.removeFromWatchlist, name='watchlist_remove'),
    # using both patterns for search either: search/?search_query=ploni, must have $ otherwise it will include urls formatted like so: search/ploni,
    # which we don't want this to include until the next url pattern
    re_path(r'^search/$', views.search, name='search'),
    # or: search/ploni
    re_path(r'^search/(?P<search_query>\w+)', views.search, name='search'),
    re_path(r'player_stats', views.allPlayerStats, name='all_player_stats'),
    
    re_path(r'^ajax/get_scheduled_games/', views.getScheduledGames, name='get_scheduled_games'),

    re_path(r'^rules/$', views.rules, name='rules'),
    re_path(r'^account/$', views.account, name='account'),
    # re_path(r'^faq/$', views.faq, name='faq'),
    re_path(r'^contact-us/', views.contact_us, name='contact_us'),



    

    path('signup/', views.signup, name='signup'),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', views.activate_account, name='activate'),
    # path('accounts/', include('django.contrib.auth.urls')),

    path('login/', views.custom_login, name='login'),
    # path('login/', auth_views.LoginView.as_view(template_name='registration/login.html'), name='login'),
    path('logout/', views.custom_logout, name='logout'),




    








    # not sure, if these should be here or project urls.py, the quickstart tutorial says here explicitly, but on the rest framework home page
    # it implies it should at the project urls.py
    # this path blows things up
    # url('^api/', include(router.urls)),

    # i guess this can also be deleted
    # path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),

    # path('players/', player_list, name='player-list'),
    # path('players/<int:pk>/', player_detail, name='player-detail'),
    # path('players/<int:pk>/team/', player_team, name='player-team'),


    # path('users/', user_list, name='user-list'),
    # path('users/<int:pk>/', user_detail, name='user-detail'),

    # path('shares/', views.ShareList.as_view(), name='share-list'),
    # path('shares/<int:pk>/', views.ShareDetail.as_view(), name='share-detail'),
    # path('shares/<int:pk>/player/', views.SharePlayer.as_view(), name='share-player'),

    # path('', views.api_root),
]


# for rest framework .json, .xml, etc.
# urlpatterns = format_suffix_patterns(urlpatterns)

nbastockmarket/nbastockmarket/urls.py
from django.contrib import admin
from django.urls import include, path

# https://www.django-rest-framework.org/ said to add these
from django.conf.urls import url, include
from django.contrib.auth.models import User
from rest_framework import routers, serializers, viewsets
from market.views import UserViewSet, GroupViewSet, PlayerViewSet, VSUserViewSet, PlayerHistoricalStatisticsViewSet, PlayerCurrentStatisticsViewSet, ShareViewSet, WatchlistDetailViewSet, UserMarketDetailsViewSet, TeamViewSet, GameViewSet, MarketViewSet

from market import views # even though on the tutorial it says project.application

# from serializers import UserSerializer
# from market.views import UserViewSet, GroupViewSet

import debug_toolbar

# Serializers define the API representation.
# class UserSerializer(serializers.HyperlinkedModelSerializer):
#     class Meta:
#         model = User
#         fields = ['url', 'username', 'email', 'is_staff']

# # ViewSets define the view behavior.
# class UserViewSet(viewsets.ModelViewSet):
#     queryset = User.objects.all()
#     serializer_class = UserSerializer

# Routers provide an easy way of automatically determining the URL conf.
# router = routers.DefaultRouter()
# router.register(r'users', UserViewSet)

# Rest Framework API
# not sure, if these should be here or project urls.py, the quickstart tutorial says here explicitly, but on the rest framework home page
# it implies it should at the project urls.py
router = routers.DefaultRouter()
router.register(r'users', UserViewSet)
router.register(r'groups', views.GroupViewSet) # not created yet
router.register(r'players', views.PlayerViewSet)
router.register(r'vsusers', views.VSUserViewSet)
router.register(r'playerhistoricalstatistics', views.PlayerHistoricalStatisticsViewSet)
router.register(r'playercurrentstatistics', views.PlayerCurrentStatisticsViewSet)
router.register(r'shares', views.ShareViewSet)
router.register(r'watchlistdetails', views.WatchlistDetailViewSet)
router.register(r'usermarketdetails', views.UserMarketDetailsViewSet)
router.register(r'teams', views.TeamViewSet)
router.register(r'games', views.GameViewSet)
router.register(r'markets', views.MarketViewSet)

urlpatterns = [
    url(r'^__debug__/', include(debug_toolbar.urls)),

    path('', views.index, name='index'),

    path('admin/', admin.site.urls),
    path('market/', include('market.urls')),
    # this is from https://docs.djangoproject.com/en/3.0/topics/auth/default/#module-django.contrib.auth.views

    # path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'), #html_email_template_name, success_url='index.html')

    path('', include('django.contrib.auth.urls')),

    url('^api/', include(router.urls)),

    
    # https://www.django-rest-framework.org/ said to add these
    # url(r'^', include(router.urls)),

    # url(r'^api-auth/', include('rest_framework.urls')),

]

nbastockmarket/market/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
# Create your models here.

from datetime import datetime
from django.db.models import Q

# change all pk_id fields to just be the default Django id, autoincrement field, must erase the table and recreate to do that, so you can wait until a checkpoint

class Team(models.Model):
    id = models.IntegerField(primary_key=True)
    sport = models.CharField(default='', max_length=200)
    full_name = models.CharField(max_length=200)
    abbreviation = models.CharField(max_length=200)
    primary_color = models.CharField(default='', max_length=200)
    secondary_color = models.CharField(default='', max_length=200)
    defensive_rank = models.IntegerField(default=0)
    image = models.CharField(default='', max_length=200)
    # should not be models.CASCADE
    next_opponent = models.ForeignKey('self', null=True, blank=True, on_delete=models.CASCADE)

    # is this needed
    # previous_opponent = models.CharField(default='', max_length=200)

class Player(models.Model):
    # change this to just be the default Django id, autoincrement field, must erase the table and recreate to do that, so you can wait until a checkpoint
    # player_id = models.IntegerField(primary_key=True)
    name = models.CharField(max_length=200)
    current_price = models.FloatField(default=1.0)#models.DecimalField(default=0, max_digits=105, decimal_places=100)
    current_performance_price = models.DecimalField(default=0, max_digits=105, decimal_places=100)
    current_player_total_shares = models.DecimalField(default=0, max_digits=105, decimal_places=100)
    current_owned_percentage_price = models.DecimalField(default=0, max_digits=105, decimal_places=100)
    sport = models.CharField(default='', max_length=200)
    image = models.CharField(default='', max_length=200) # how to represent
    # team_image = models.CharField(default='', max_length=200) # how to represent
    position = models.CharField(default='', max_length=200)
    number = models.IntegerField(default=0)
    height = models.CharField(default='', max_length=200)
    weight = models.CharField(default='', max_length=200)
    delta = models.FloatField(default=0.0)

    team = models.ForeignKey(Team, on_delete=models.CASCADE)

    career_start_year = models.IntegerField(default=2019)
    career_end_year = models.IntegerField(default=2019)
    is_active = models.BooleanField(default=True)

    owner = models.ForeignKey(User, related_name='players', on_delete=models.CASCADE)
    # next_opponent = models.ForeignKey(Team, max_length=200, on_delete=models.CASCADE)
    # to_add to another table or this table?
    # ppg, apg, rpg, per, etc., for season? for career?
    def get_fields(self):
        return [(field.name, field.value_to_string(self)) for field in Player._meta.fields]
    # def __str__(self):
    #     return self.name
    def get_main_stats(self):
        return 'hello'#self.name#.all()#.filter(stat_name="nba_total_points")

class VSUser(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    birth_date = models.DateField(null=True, blank=True) # idk what null=True and blank=True means
    address = models.CharField(max_length=200)
    city = models.CharField(max_length=200)
    state = models.CharField(max_length=200)
    zipcode = models.CharField(max_length=200)
    level = models.CharField(max_length=200)
    money_in_the_bank = models.FloatField(default=0.0)
    # def __str__(self):
    #     return self.username

class PlayerHistoricalStatistics(models.Model):
    stat_id = models.AutoField(primary_key=True) #// some interesting choices here
    stat_name = models.CharField(default="", max_length=200)
    stat_value = models.FloatField(default=0.0) #, max_digits=125, decimal_places=100)
    stat_type = models.CharField(default="", max_length=200)  #//maybe
    stat_datetime_of_game = models.DateTimeField(default=datetime.now, blank=True)
    stat_created_at = models.DateTimeField(default=datetime.now, blank=True)
    player = models.ForeignKey(Player, on_delete=models.CASCADE)


class PlayerCurrentStatistics(models.Model):
    # stat_id = models.IntegerField(primary_key=True) #// some interesting choices here
    stat_name = models.CharField(default="", max_length=200)
    stat_value = models.FloatField(default=0.0) #, max_digits=125, decimal_places=100)
    stat_type = models.CharField(default="", max_length=200)  #//maybe
    stat_created_at = models.DateTimeField(default=datetime.now, blank=True)
    player = models.ForeignKey(Player, on_delete=models.CASCADE) #, related_name='player_current_stats'

class Share(models.Model):
    # should player_id, really be OneToOne, because even though theres many per player, but theres only one within each User per player
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    player = models.ForeignKey(Player, on_delete=models.CASCADE)
    number_of_shares = models.IntegerField(default=0)
    # maybe should be integer field that is x100 for performance($23.45 would just be stored as 2345)
    bought_price = models.FloatField(default=0.0)#models.DecimalField(default=0, max_digits=105, decimal_places=100) # IntegerField
    # def __str__(self):
    #     return self.player_symbol
    # def player_sport(self):
    #     return self.sport

class WatchlistDetail(models.Model):
    #see here which one you really want for on_delete, https://docs.djangoproject.com/en/3.0/ref/models/fields/#django.db.models.ForeignKey.on_delete
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    player = models.ForeignKey(Player, on_delete=models.CASCADE)

class UserMarketDetails(models.Model):
    # user_market_id = models.IntegerField(primary_key=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    money_in_account = models.IntegerField(default=0)
    # def __str__(self):
    #     return 'no string value in models'

class OrderBook(models.Model):
    # order_id = models.IntegerField(primary_key=True)
    user_id = models.ForeignKey(User, default=-1, on_delete=models.CASCADE)
    datetime_stamp = models.DateTimeField('datetime ordered')
    player_symbol = models.CharField(max_length=200)
    bid_or_ask_side = models.CharField(max_length=200)
    price = models.IntegerField(default=0.0)
    quantity = models.IntegerField(default=0)

        
class Game(models.Model):
    # game_id = models.IntegerField(primary_key=True)
    sport = models.CharField(max_length=200)
    home_team = models.ForeignKey(Team, null=True, blank=True, related_name='home_team', on_delete=models.CASCADE)
    away_team = models.ForeignKey(Team, null=True, blank=True, related_name='away_team', on_delete=models.CASCADE)
    game_time = models.DateTimeField('game time', null=True, blank=True)

class Market(models.Model):
    total_raw_prices = models.DecimalField(default=0, max_digits=105, decimal_places=100)
    # total_share_prices = models.DecimalField(default=0, max_digits=105, decimal_places=100)
    total_number_of_shares = models.DecimalField(default=0, max_digits=205, decimal_places=100)
    # total_price = models.DecimalField(default=0, max_digits=105, decimal_places=100)

nbastockmarket/market/templates/market/account_confirmation_email.html
{% autoescape off %}
Hi {{ user.username }},
Welcome to Venture Sports.
Please click on the link to confirm your registration,

http://{{ domain }}{% url 'market:activate' uidb64=uid token=token %}
{% endautoescape %}

nbastockmarket/market/templates/market/footer.html
<div id="footer">
    <a href="">Contact</a>
    <a href="">About Us</a>
    <a href="">FAQ</a>
    <a href="">Site Map</a>
    <a href="">Site Map</a>
    <a href="">Site Map</a>
    <a href="">Site Map</a>
    <a href="">Site Map</a>
    <a href="">Site Map</a>
</div>
<style type="text/css">
    #footer {
        width: 100%;
        height: 400px;
        background-color: #404040;
    }
</style>

nbastockmarket/market/templates/market/privacy_policy.html
<!DOCTYPE html>
<html>
<head>
    <title>Privacy Policy</title>
</head>
<body>
Third party vendors, including Google, use cookies to serve ads based on a user's prior visits to your website or other websites.
Google's use of advertising cookies enables it and its partners to serve ads to your users based on their visit to your sites and/or other sites on the Internet.
Users may opt out of personalized advertising by visiting Ads Settings. (Alternatively, you can direct users to opt out of a third-party vendor's use of cookies for personalized advertising by visiting www.aboutads.info.)
If you have not opted out of third-party ad serving, the cookies of other third-party vendors or ad networks may also be used to serve ads on your site, which should also be disclosed in your privacy policy in the following manner:

Notify your site visitors of the third-party vendors and ad networks serving ads on your site.
Provide links to the appropriate vendor and ad network websites.
Inform your users that they may visit those websites to opt out of the use of cookies for personalized advertising (if the vendor or ad network offers this capability). Alternatively, you can direct users to opt out of some third-party vendors’ uses of cookies for personalized advertising by visiting www.aboutads.info.
Because publisher sites and laws across countries vary, we're unable to suggest specific privacy policy language. However, you may wish to review resources such as the Network Advertising Initiative for guidance on drafting a privacy policy. For additional details regarding cookie consent notices, please refer to cookiechoices.org.
</body>
</html>

nbastockmarket/market/templates/market/search.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Search</title>
    {% load static %}
    <link rel="icon" href="{% static "market/images/other/venture_sports_primary_logo.png" %}">
  </head>
  <body>
    {% include "market/header.html" with scheduled_games=scheduled_games list_of_names=list_of_names %}

    {% load custom_tags %}

<!-- {{re}} -->
<!-- {{query}} -->
<!-- {{ player_list.count }} -->
<div id="stock-cards-container">
    {% for player in player_list  %}
    {# with current_player_id_dict=search_results_dict|keyvalue:player.id current_player_id=player.id #}  
    <div class="stock-card" style="background: linear-gradient(to bottom, transparent 0%, transparent 33%, {{ player.team.primary_color }} 100%) no-repeat,black;">
        <a href="{% url 'market:player_detail' player.id %}"><span></span></a>
        <div id="images-container">
            <div id="logo-image-container">
                <img src="/static/market/images/other/{{ player.sport }}_logo.png">
            </div>
            <div id="team-image-container">
                <img src="/static/market/images/teams/{{ player.sport }}_teams/{{ player.team.full_name|tovariablename }}.png">
            </div>
            <div id="player-image-container">
                <img src="/static/market/images/players/{{ player.sport }}/{{ player.name|tovariablename }}.png">
            </div>
            
        </div>
        <div id="text-container">
            <div id="primary-text-container">
                <h1>{{ player.name|title|fitword:14 }}</h1>
                {% if player.delta >= 0 %}
                <h3>${{ player.current_performance_price|todollarsandcents }}<span class="positive"><i class="fa fa-angle-up"></i>(+${{ player.delta }})</span></h3>
                {% else %}
                <h3>${{ player.current_performance_price|todollarsandcents }}<span class="negative"><i class="fa fa-angle-down"></i>(-${{ player.delta }})</span></h3>
                {% endif %}
            </div>
            <div id="statistics-text-container">
                <table>
                    <thead style="background-color:{{ player.team.primary_color }};color:{{ primary_design_color }};">
                        <tr>
                        {% if player.sport|lower == "nba" %}
                            <th>PPG</th>
                            <th>RPG</th>
                            <th>APG</th>
                        {% elif player.sport|lower == "mlb" %}
                            {% if player.position|lower == "p" or player.position|lower == "pitcher" %}
                            <th>W</th>
                            <th>L</th>
                            <th>ERA</th>
                            <!-- <th>K/9</th>
                            <th>WHIP</th> -->
                            {% else %}
                            <th>BA</th>
                            <th>RBI</th>
                            <th>HR</th>
                            {% endif %}
                        {% else %}
                            {% if player.position|lower == "qb" %}
                            <th>YPG</th>
                            <th>TD</th>
                            <th>INT</th>
                            {% elif player.position|lower == "rb" %}
                            <th>YPG</th>
                            <th>TD</th>
                            <th>F</th>
                            {% elif player.position|lower == "wr" or player.position|lower == "te" %}
                            <th>YPG</th>
                            <th>REC</th>
                            <th>TD</th>
                            {% else %}
                            <th>TKL</th>
                            <th>INT</th>
                            <th>S</th>
                            {% endif %}
                        {% endif %}
                        </tr>
                    </thead>
                    <tbody style="background-color:{{ primary_design_color }};color:{{ player.team.primary_color }};">
                        <tr>    
                        {% if player.sport|lower == "nba" %}
                        {% for stat in player.playercurrentstatistics_set.all %}
                        {% if stat.stat_name == "nba_total_points" %}
                            <td>{{ stat.stat_value }}</td>
                        {% endif %}
                        {% if stat.stat_name == "nba_total_rebounds" %}
                            <td>{{ stat.stat_value }}</td>
                        {% endif %}
                        {% if stat.stat_name == "nba_assists" %}
                            <td>{{ stat.stat_value }}</td>
                        {% endif %}
                        {% endfor %}
                        {% endif %}
                        
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    {# endwith #}
    {% endfor %}
</div>
<!-- {{query}} -->
<!-- {{ search_results_dict }} -->
</body>
</html>
<style type="text/css">
body {
    background-color: {{ primary_design_color }}; /*#c6c6ee;*/
}

#stock-cards-container {
    float: left;
    width: 90%;
    margin-left: 5%;
    margin-right: 5%;
    /*margin: auto;*/ /*could alsohave this if needed*/
}


@media only screen and (min-width:1000px) /* make sure this is good, because it's a balagan by the chrome debugger */
{
    #stock-cards-container
    {
        float: left; 
        width: 60%;
        margin-left: 20%;
        margin-right: 20%;
    }
}

.stock-card {
    /*margin:auto; makes it in the middle*/
    margin-bottom: 40px;
    position: relative; /* must be relative so that only the div - and nothing outside it - is the a tag link clickable*/
    width: 100%;
    height: 325px;
    /*background-color: blue;*/
    /* make this correspond to team color?*/
    border-radius: 15px;
    box-shadow: 0px 0px 10px black; /* range from 0 - 1 */ /* 0px 8px 16px 0px rgba(0,0,0,1); */
}

@media only screen and (min-width:1000px) /* make sure this is good, because it's a balagan by the chrome debugger */
{
    .stock-card
    {
        height: 165px;
        margin-bottom: 10px;

    }
}

#images-container {
    float: left;
    width: 25%;
    margin-right: 10%;
    height: 100%;
    /*text-align: center; actually works for images, who would have thought */
}

@media only screen and (min-width:1000px) /* make sure this is good, because it's a balagan by the chrome debugger */
{
    #images-container {
        float: left;
        width: 15%;
        margin-right: 3%;
        height: 100%;
        /*text-align: center; actually works for images, who would have thought */
    }
}

#logo-image-container {
    float: left;
    width: 80%;
    height: 20%;
    margin-left: 20%;
    margin-bottom: 10px;
}

@media only screen and (min-width:1000px) /* make sure this is good, because it's a balagan by the chrome debugger */
{
    #logo-image-container {
        float: left;
        width: 80%;
        height: 20%;
        margin-left: 20%;
        margin-bottom: 5px;
    }
}

#logo-image-container img {
    float: left;
    height: 100%;
    /*width: 20%;*/
}

#team-image-container {
    float: left;
    width: 80%;
    height: 30%;
    margin-left: 20%;
}

#team-image-container img {
    float: left;
    height: 100%;
}


#player-image-container {
    float: left;
    width: 80%;
    height: 50%;
    margin-left: 20%;
}

#player-image-container img {
    float: left;
    height: 94%;
}

/*@media only screen and (min-width:1000px)  make sure this is good, because it's a balagan by the chrome debugger 
{
    #images-container div img {
        float: left;
        width: 60%;
        margin-left: 20%;
        margin-right: 20%;
    }
}
*/


#text-container {
    float: left;
    width: 65%;
    height: 100%;
    /*text-align: center; actually works for images, who would have thought */
}

@media only screen and (min-width:1000px) /* make sure this is good, because it's a balagan by the chrome debugger */
{
    #text-container {
        float: left;
        width: 82%;
        height: 100%;
        /*text-align: center; actually works for images, who would have thought */
    }
}



#primary-text-container {
    float: left;
    width: 100%;
    height: 50%;
    /*margin-top: 10px;*/
    /*margin-bottom: 10px;*/
    border-radius: 5px;
    /*background-color: {{ secondary_design_color }};*/
    color: {{ primary_design_color }};
}

@media only screen and (min-width:1000px) /* make sure this is good, because it's a balagan by the chrome debugger */
{
    #primary-text-container {
        float: left;
        width: 65%;
        height: 100%;
        /*margin-top: 10px;*/
        /*margin-bottom: 10px;*/
        border-radius: 5px;
        /*background-color: {{ secondary_design_color }};*/
        color: {{ primary_design_color }};
    }
}

#primary-text-container h1 {
    font-size: 4.5em;
}

@media only screen and (min-width:1000px) /* make sure this is good, because it's a balagan by the chrome debugger */
{
    #primary-text-container h1 {
        font-size: 3em;
    }
}


#primary-text-container h3 {
    font-size: 3.5em;
}

@media only screen and (min-width:1000px) /* make sure this is good, because it's a balagan by the chrome debugger */
{
    #primary-text-container h3 {
        font-size: 2.5em;
    }
}

#statistics-text-container {
    float: left;
    width: 100%;
}

@media only screen and (min-width:1000px) /* make sure this is good, because it's a balagan by the chrome debugger */
{
    #statistics-text-container {
        float: left;
        width: 35%;
    }
}

#statistics-text-container table {
    float: left;
    width: 65%;
    margin-left: 0%;
    /*margin-right: 5%;*/
    margin-top: 10px;
    margin-bottom: 20px;
    background-color: {{ secondary_design_color }};
    color: {{ primary_design_color }};
    border-radius: 5px;
    border: 1px solid {{ primary_design_color }};
    overflow: hidden;
    text-align: center;
    border-collapse: collapse;
    /* box-shadow: 0px 0px 10px black; range from 0 - 1 0px 8px 16px 0px rgba(0,0,0,1); */
}

@media only screen and (min-width:1000px) /* make sure this is good, because it's a balagan by the chrome debugger */
{
    #statistics-text-container table {
        float: left;
        width: 92.5%;
        margin-left: 2.5%;
        margin-right: 5%;
        margin-top: 40px;
        margin-bottom: 20px;
        background-color: {{ secondary_design_color }};
        color: {{ primary_design_color }};
        border-radius: 5px;
        border: 1px solid {{ primary_design_color }};
        overflow: hidden;
        text-align: center;
        border-collapse: collapse;
        /* box-shadow: 0px 0px 10px black; range from 0 - 1 0px 8px 16px 0px rgba(0,0,0,1); */
    }
}

#statistics-text-container thead {
    background-color: {{ secondary_design_color }};
    color: {{ primary_design_color }};
    border-radius: 5px;
    border: 1px solid {{ primary_design_color }};
    overflow: hidden;
    text-align: center;
    border-collapse: collapse;
}

#statistics-text-container thead th {
    border: 1px solid {{ secondary_design_color }};
    overflow: hidden;
    text-align: center;
    border-collapse: collapse;
    font-size: 2.5em;
}

@media only screen and (min-width:1000px) /* make sure this is good, because it's a balagan by the chrome debugger */
{
    #statistics-text-container thead th {
        border: 1px solid {{ secondary_design_color }};
        overflow: hidden;
        text-align: center;
        border-collapse: collapse;
        font-size: 1em;
    }
}

#statistics-text-container tbody {
    /*background-color: white;
    color: black;*/

    background-color: {{ primary_design_color }};
    color: {{ secondary_design_color }};
}

#statistics-text-container tbody td {
    border: 1px solid {{ secondary_design_color }};
    overflow: hidden;
    text-align: center;
    border-collapse: collapse;
    font-size: 3em;
}

@media only screen and (min-width:1000px) /* make sure this is good, because it's a balagan by the chrome debugger */
{
    #statistics-text-container tbody td {
        border: 1px solid {{ secondary_design_color }};
        overflow: hidden;
        text-align: center;
        border-collapse: collapse;
        font-size: 1em;
    }
}
    


.stock-card p {
    float:left;
    margin: 5px;
    color: {{ primary_design_color }};
}

/* taken from https://stackoverflow.com/questions/796087/make-a-div-into-a-link */
.stock-card a span {
  position:absolute; 
  width:100%;
  height:100%;
  top:0;
  left: 0;
  z-index: 1;
  /* fixes overlap error in IE7/8, 
     make sure you have an empty gif */
  background-image: url('empty.gif');
}

.negative {
    color: {{ negative_color }};
}

.positive {
    color: {{ positive_color }};
}
</style>